translations = {
    "universal":{
    "names": ["TFalcon","BrownStar"],
    },
    "en-US": {
        "helpHeader": "Help",
        "helpHover": "To see when the timer runs out, you can hover/click on the timestamp.\nTo view the command used click the blue text `/countdown`\nYou can use app commands by right click/long pressing on a countdown, pick apps, and then the command.\n`MENTION_EVERYONE` permission needed to mention people at end of countdown.",
        "helpDesc": "This bot has the following commands:",
        "helpLeftTitle": "/Timeleft",
        "helpLeftDesc": "Shows the exact time left for a countdown.",
        "helpCountdownTitle": "/Countdown",
        "helpCountdownDesc": "Countdown will show the remaining time until the date you entered, or for the duration you specify. Its default timezone is ET. Repeatable with `times` option.",
        "helpListTitle": "/List",
        "helpListDesc": "It will show you all active countdowns in the channel/guild or from you depending on subcommand.",
        "helpDeleteTitle": "/Delete",
        "helpDeleteDesc": "To use this with other than `mine` you need to have the `MANAGE_MESSAGE` permission.\n`single` ~ Pick one of the list presented to you. `/list` for more info.\n`mine` ~ Delete the countdown you created.\n`channel` ~ Deletes all countdowns in this channel.\n`guild` ~ Deletes all countdowns in this guild.",
        "helpHelpTitle": "/Help",
        "helpHelpDesc": "Shows this help message",
        "helpMentionTitle": "Mention",
        "helpMentionDesc": "To be able to mention people at the end of the countdown you currently need to have the `MENTION_EVERYONE` premission",
        "helpLinksTitle": "Links",
        "helpLinksDesc": "[Discord Support]( https://discord.gg/YTxTms4Sp7 'Join the support guild!') | [Invite the Bot](https://top.gg/bot/1015703443358363789) | [Patreon](https://patreon.com/HourglassTimelord)",
        "helpTranslateTitle": "/Translate",
        "helpTranslateDesc": "Allows you as an administrator to switch the language of the bot",
        "helpFooter0": " - thank you for supporting the bot on patreon.",
        "helpFooter1": "Thanks Zetas2 for developing this bot",
        "helpFooter2": "Thanks Biz for being a legend",
        "helpFooter3": "Thanks Pocket for outliving all the mess",
        "helpFooter4": "Thanks Stryker for tasting my spaghetti",
        "helpFooter5": "Thanks Midnightoel for causing me problems to solve",
        "helpFooter6": "Thanks Patreons for supporting the bot",
        "helpFooter7": "Thanks Zetas2 for translating to english", # Edit to your name and language
        "premiumTitle": "Premium info",
        "premiumDesc": "To get premium you can head over to [Patreon](https://www.patreon.com/HourglassTimelord)",
        "premiumMultipleTitle":"Can I have premium in multiple guilds?",
        "premiumMultipleDesc":"Yes, however it is a bit tricky. Ping <@238006908664020993> in the [Discord Support Guild](https://discord.gg/YTxTms4Sp7) to learn more.",
        "premiumPickTitle":"How do I pick what guild?",
        "premiumPickDesc":"You can use the command /makethispremium and it will make the guild you use it in to be premium. \n**BEWARE!** There is a cooldown between uses of it.",
        "premiumActivateTitle":"How do I activate it?",
        "premiumActivateDesc":"Unfortunatly there isnt a good way of doing this yet. For now ping either <@238006908664020993> or <@729791860674920488> after reciving the patreon role in the [Discord Support Guild](https://discord.gg/YTxTms4Sp7)",
        "premiumWhyTitle":"Why premium?",
        "premiumWhyDesc":"Premium gives you access to:\n• More countdowns in a guild\n• Adding images at the end of a countdown\n• Repeating countdowns\n• Custom message after countdown",
        "premiumFooter": "Thanks for considering supporting this bot",
        "botstatTitle": "BOT STATS",
        "botstatDesc": "This is the current status of the bot",
        "permsFixed": "The permissions are fixed!",
        "permsNotFixed": "Sorry, I couldnt fix the permissions. (Am I allowed to edit channel?)",
        "CPU": "CPU",
        "RAM": "RAM",
        "storage": "Storage used",
        "active": "Active countdowns",
        "uptime": "Uptime",
        "ping": "Ping",
        "log": "Log size",
        "ms": "ms",
        "rows": "rows",
        "multiple": "(s)",
        "guild": "Guild",
        "channel": "Channel",
        "done": "A countdown is done!",
        "message": "Message",
        "original": "Original message",
        "repeat": "Repeating",
        "repeatStart": "This countdown will be repeated",
        "repeatEnd": "time(s) more. Next time is",
        "created": "It was started by",
        "translated": "translated the bot to",
        "wasDeleted": "was deleted by",
        "updated": "was updated to:",
        "exact": "Exact time from start:",
        "exactLeft": "Exact time left for countdown",
        "sent": "Sent",
        "kept": "All countdowns are kept",
        "deleted": "DELETED",
        "jump": "Click here to jump to the message",
        "countdown": "Countdown",
        "timestamp": "Timestamps",
        "timestampList": "Here is a list of all timestamps:",
        "timeRemain":"Time remaining:",
        "dateTime":"Date with time:",
        "date":"Date:",
        "dateMonth":"Date with month spelled out:",
        "time":"Time:",
        "timeWithSecond":"Time with seconds:",
        "dateTimeWeek":"Date with time and day of week:",
        "error": "SOMETHING WENT WRONG",
        "errDm": "You cant use this in DMs",
        "errListDm": "Sorry, only /list channel works in DMs",
        "errPremiumDm": "You cant use premium features in DMs",
        "errPremium": "Sorry, you tried to use a premium only feature:",
        "errPremiumReuse": "Sorry, you need to be a premium user to use this command. Or wait 2 days since you last used it",
        "errPremiumImage": "adding image",
        "errPremiumRepeat": "repeating timer",
        "errPremiumCustomMsg": "custom message after complete",
        "errImage": "You need to send a link to the image",
        "errView": "I am missing the permission to view the channel. Please give me it!",
        "errPerms": "In order to preform this action I need view and send embeds/messages permissions added __**directly**__ to this channel.",
        "errLength": "Minimum length of a countdown is one minute",
        "errMention": "You dont have permission to ping that role",
        "errDate": "Sorry, I dont understand that date!",
        "errPast": "You cant set time in the past. Try be more specific about your time.",
        "errOption": "Please use one of the options",
        "errDelete": "An error occurred (could be that there is none to delete)",
        "errNoPerm": "Sorry, you need `MANAGE_MESSAGES` to use this, unless you want to delete your own",
        "errNoActive": "You can ony use this on active countdowns.",
        "errNotFound": "The countdown was not found.",
        "errManageGuild": "Sorry, I need to be able to manage guild to use this command. I use the guilds language to know what language to operate on.",
        "errNoAdmin": "Sorry, you need to be administrator to use this command",
        "errDev": "Sorry, you need to be the dev to use this command",
        "deleteConfirmGuild": "Are you sure you want to delete all your countdowns in this guild?",
        "deleteConfirmChannel": "Are you sure you want to delete all your countdowns in this channel?",
        "maxDm": "Max countdowns in dms reached. Delete one or wait for one to run out to add more.",
        "maxGuild": "Increased amount of countdowns in this guild. Get premium or delete some of the active ones.",
        "maxChannel": "Increased amount of countdowns in this channel. Get premium or delete some of the active ones.",
        "place": "in this",
        "placeUser":"from you",
        "activeTitle": "ACTIVE COUNTDOWNS",
        "activeDesc":"These are the countdowns active",
        "timeDay": "day(s)",
        "timeHour": "hour(s)",
        "timeMinute": "minute(s)",
        "timeSecond": "second(s)",
    },
}
