translations = {
    "en-US": {
        "helpHeader": "Help",
        "helpHover": "To see when the timer runs out, you can hover/click on the timestamp.\nTo view the command used click the blue text `/countdown`\nYou can use app commands by right click/long pressing on a countdown, pick apps, and then the command.\n`MENTION_EVERYONE` permission needed to mention people at end of countdown.",
        "helpDesc": "This bot has the following commands:",
        "helpLeftTitle": "/Timeleft",
        "helpLeftDesc": "Shows the exact time left for a countdown.",
        "helpCountdownTitle": "/Countdown",
        "helpCountdownDesc": "Countdown will show the remaining time until the date you entered, or for the duration you specify. Its timezone is UTC. Repeatable with `times` option.",
        "helpListTitle": "/List",
        "helpListDesc": "It will show you all active countdowns in the channel/guild or from you depending on subcommand.",
        "helpDeleteTitle": "/Delete",
        "helpDeleteDesc": "To use this with other than `mine` you need to have the `MANAGE_MESSAGE` permission.\n`single` ~ Pick one of the list presented to you. `/list` for more info.\n`mine` ~ Delete the countdown you created.\n`channel` ~ Deletes all countdowns in this channel.\n`guild` ~ Deletes all countdowns in this guild.",
        "helpHelpTitle": "/Help",
        "helpHelpDesc": "Shows this help message",
        "helpMentionTitle": "Mention",
        "helpMentionDesc": "To be able to mention people at the end of the countdown you currently need to have the `MENTION_EVERYONE` premission",
        "helpLinksTitle": "Links",
        "helpLinksDesc": "[Discord Support]( https://discord.gg/YTxTms4Sp7 'Join the support guild!') | [Invite the Bot](https://top.gg/bot/1015703443358363789) | [Patreon](https://patreon.com/HourglassTimelord)",
        "helpTranslateTitle": "/Translate",
        "helpTranslateDesc": "Allows you as an administrator to switch the language of the bot",
        "helpFooter1": "Thanks Zetas2 for developing this bot",
        "helpFooter2": "Thanks Biz for being a legend",
        "helpFooter3": "Thanks Pocket for outliving all the mess",
        "helpFooter4": "Thanks Stryker for tasting my spaghetti",
        "helpFooter5": "Thanks Midnightoel for causing me problems to solve",
        "helpFooter6": "Thanks Patreons for supporting the bot",
        "helpFooter7": "Thanks TFalcon for being the first super patreon.",
        "done": "A countdown is done!",
        "created": "It was started by",
    },
}
