translations = {
    "en-US": {
        "helpHeader": "Help",
        "helpHover": "To see when the timer runs out, you can hover/click on the timestamp.\nTo view the command used click the blue text `/countdown`\nYou can use app commands by right click/long pressing on a countdown, pick apps, and then the command.\n`MANAGE_MESSAGES` permissions needed to mention people at the end of the countdown.",
        "helpDesc": "\n**This bot has the following commands:**",
        "helpLeftTitle": "/timeleft *(timeleftthis)*",
        "helpLeftDesc": "Shows the exact time left for a countdown.",
        "helpCountdownTitle": "/countdown",
        "helpCountdownDesc": "Creates a countdown displaying the remaining time to the entered date or duration specified. Its timezone is UTC. They can be repeated by using the times option.",
        "helpListTitle": "/list",
        "helpListDesc": "List all active countdowns in the channel/guild or from you depending on subcommand.",
        "helpDeleteTitle": "/delete *(deletethis)*",
        "helpDeleteDesc": "To use this with other than `mine` you need to have the `MANAGE_MESSAGE` permission.\n`single` ~ Pick one of the list presented to you. `/list` for more info.\n`mine` ~ Delete the countdown you created.\n`channel` ~ Deletes all countdowns in this channel.\n`guild` ~ Deletes all countdowns in this guild.",
        "helpHelpTitle": "/help",
        "helpHelpDesc": "Shows this help message.",
        "helpLinksDesc": "[Discord Support](https://discord.com/invite/b2fY4z4xBY 'Join the support guild!') | [Invite the Bot](https://top.gg/bot/1015703443358363789) | [Patreon](https://www.patreon.com/livecountdownbot)",
        "helpTranslateTitle": "/translate",
        "helpTranslateDesc": "Allows you as an administrator to switch the language of the bot",
        "helpFooter": "Thanks Zetas2 for translating to English",
        "done": "A countdown is done!",
        "created": "It was started by",
    },
}
