translations = {
    "en-US": {
        "helpHeader": "Help",
        "helpHover": "To see when the timer runs out, you can hover/click on the timestamp.",
        "helpDesc": "This bot has the following commands:",
        "helpLeftTitle": "/Timeleft",
        "helpLeftDesc": "Shows the exact time left for a countdown.",
        "helpCountdownTitle": "/Countdown",
        "helpCountdownDesc": "Countdown will show the remaining time until the date you entered, or for the duration you specify. Its timezone is UTC. They can be repeated by using the times option.",
        "helpListTitle": "/List",
        "helpListDesc": "It will show you all active countdowns in the channel/guild or from you depending on subcommand.",
        "helpDeleteTitle": "/Delete",
        "helpDeleteDesc": "To use this with other than *mine* you need to have the `MANAGE_MESSAGE` permission.\n*Single*\nPick one of the list presented to you. To get more info about what countdown it is, use /list.\n*Mine*\nDelete the countdown you created.\n*Channel*\nDeletes all countdowns in this channel.\n*Guild*\nDeletes all countdowns in this guild.",
        "helpHelpTitle": "/Help",
        "helpHelpDesc": "Shows this help message",
        "helpLinksTitle": "/Links",
        "helpLinksDesc": "[Discord Support](https://discord.com/invite/b2fY4z4xBY 'Join the support guild!') | [Invite the Bot](https://top.gg/bot/710486805836988507) | [Patreon](https://www.patreon.com/livecountdownbot)",
        "helpTranslateTitle": "/Translate",
        "helpTranslateDesc": "Allows you as an administrator to switch the language of the bot",
        "helpFooter": "Thanks Zetas2 for translating to English",
        "done": "A countdown is done!",
        "created": "It was started by",
    },
}
